### ISSUE TITLE
Container not found

### ISSUE THREAD

**Issue by ghost** [marcqualie/rancher-shell#2]
Hi,

I am trying to use your rancher client, however, when I execute rancher-shell exec -p 111 -s 12345 -c 123456 ls is telling me Container not found.

[2017-02-02 16:34:20] ERROR -- : could not find container: 123456

Do you have an idea why this might be happening?

Also, could you please make it more clearer if whether we have to use Rancher variables such as: Project ID, Stack ID and Container ID or they are Project name, Stack name and Container name?

Thanks

**Comment by marcqualie** [comment]
It's designed to work with names rather than IDs.

`rancher-shell exec -p ProjectNameFromConfig -s StackName -c FullContainerName`

For example I use this one one of my projects

`rancher-shell exec -p gostatic -s staging -c staging-clock_1`

That lets me boot into the "clock" container within the staging stack. It uses the credentials stored in `.rancher.yml` from the "gostatic" configuration.

I will update the documentation to make this more clear with examples.

**Comment by scornea** [comment]
@marcqualie Thank you for your quick response! It was very helpful and I can successfully now connect to the container, however, when I exec ls on the container I get `stty: standard input: Not a tty` is there a way to force tty? 

PS. All my container have tty: true

**Comment by marcqualie** [comment]
Not configurable as of now but it may be something I can add in a patch. Does it function correctly but shows a warning, or can you not communicate with the container at all?

**Comment by scornea** [comment]
@marcqualie Well it connects but it doesn't "run" the command as where the command should be there's:

[2017-02-02 18:06:12]  INFO -- : container = 1ixxxxx
[2017-02-02 18:06:12] DEBUG -- : running command: echo hello
[2017-02-02 18:06:12]  INFO -- : connecting to wss://url/v1/exec/ ...
[2017-02-02 18:06:13]  INFO -- : listening
stty: standard input: Not a tty
[2017-02-02 18:06:13]  INFO -- :   connected!

**Comment by marcqualie** [comment]
I will try to address this within the next 24 hours. Could you confirm which version you are using via `rancher version`?

Also to clarify, could you show me the tty settings that you have on the container within rancher so I can replicate on my end.

**Comment by scornea** [comment]
@marcqualie The rancher version I am using is 1.2.0

Aso, regarding the tty below is a screenshot of what my Rancher settings are for that specific container.

![screen shot 2017-02-04 at 11 15 45](https://cloud.githubusercontent.com/assets/22293248/22618056/51d95324-eacb-11e6-8356-bb236f3e4b31.png)

**Comment by marcqualie** [comment]
Apologies for the delay.

I've not been unable to replicate this with any set of interactive/tty combinations. Were you ever able to get this working? I have a suspicion that Gitlab CI may not have a tty which may prevent the input listener from attaching.

There is a line of code `system("stty raw")` which prevents `ctrl + c` from closing the running session and instead passes it to the underlying command. Since this line of code comes right after "listening" and before connected I believe the problem lies on your system rather than rancher, or this tool.
